### ISSUE TITLE
neo-sharp node Broken

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-sharp#344]
After last commit https://github.com/CityOfZion/neo-sharp/commit/f34a24c0db88b52880c824beade6cfa13fe8a8d6 the Node compiles correctly but it does not work when we try to start it.

```
root@1d8115282070:/home/neo-sharp# dotnet NeoSharp.Application.dll
Neo-Sharp

Unhandled Exception: System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: currentBlock) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: currentBlock
   at NeoSharp.Core.Blockchain.Processing.BlockProcessor.Run(Block currentBlock) in /repo/neo-sharp/src/NeoSharp.Core/Blockchain/Processing/BlockProcessor.cs:line 52
   at NeoSharp.Core.Blockchain.Blockchain.InitializeBlockchain() in /repo/neo-sharp/src/NeoSharp.Core/Blockchain/Blockchain.cs:line 67
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NeoSharp.Application.Client.Prompt.StartPrompt(String[] args) in /repo/neo-sharp/src/NeoSharp.Application/Client/Prompt.cs:line 136
   at NeoSharp.Application.Program.Main(String[] args) in /repo/neo-sharp/src/NeoSharp.Application/Program.cs:line 28
Aborted (core dumped)
```

**Comment by osmirnov** [comment]
it works for me on dev branch. Are you using specific commit?

**Comment by nunojusto** [comment]
I'm using dev. Could it be a runtime container only problem? Maybe... I'm investigating.

**Comment by nunojusto** [comment]
I've tried to run inside the Full SDK container and it's failing also with the same error.
Something is missing here. When you say it works. What really works in your env? You compile and run the node?

**Comment by osmirnov** [comment]
Yes, I've tried to debug - no issue. I went into the console to run ```dotnet NeoSharp.Application.dll``` - no issue.

**Comment by nunojusto** [comment]
OK, thanks.
So, runs out of the containers but not inside. I'm in it...

**Comment by aboimpinto** [comment]
I got this issue too and spend some time debugging it and found the problem

the test that @nunojusto is trying to create is valid and make all the sense and when this test fail we should take it very serious and not just saying: "works in my machine".
To help debug this situations better I instruct @nunojusto to create a node with Remote-Debugging on and developers can attach their VisualStudio to the node and debug it.

Going back to the issue, on the 7 of September, @osmirnov you made a piece of code that is causing this issue.
On the class BlockProcessor in the method Run you replace this code:
_blockPool.CurrentBlock = currentBlock;
with
_currentBlock = currentBlock ?? throw new ArgumentNullException(nameof(currentBlock));

and this is the line that is giving the error.
This issue only happen  when you start your node without no genesis block mean that you have to delete all the RockDb files.
This is the environment that @nunojusto has in his containers: **a clean environment**

I want to notice that this is not "pointing fingers" to know one, but, to highlight that the work that @nunojusto is doing is very valuable and before we create the PR we should run his containers in order to guarantee that everything still working: 
* node is compiling - doing by travis, 
* node starts - with the containers, 
* node  syncs - on development

**Comment by nunojusto** [comment]
Thanks @aboimpinto. I was becoming insane, testing even different versions of Dotnet...yada, yada.

**Comment by osmirnov** [comment]
You were right, guys. I have already genesis block in my local env. Only start with empty db produces this result. I think it is great the containers helped us to spot this. Good work!
